In [1]:
import torch
from utils.draw import draw_squares
from utils.square import SquareDataset
from torch.utils.data import DataLoader

In [3]:
squares = SquareDataset(1280)
for i in range(5):
   print(squares[i])

(tensor([146., 198., 170., 197., 100.,  25.,  16.,  78.,  21.]), tensor([1., 0., 0.]))
(tensor([226., 131.,  24., 221.,  54., 116.,  80., 121.,  10.]), tensor([0., 1., 0.]))
(tensor([  2., 110., 181., 117., 194., 153.,  14., 151.,  96.]), tensor([0., 1., 0.]))
(tensor([230.,  30., 236., 135.,  95., 126., 160.,  64.,  26.]), tensor([1., 0., 0.]))
(tensor([173., 249.,  12., 150., 111.,  19., 196., 106., 227.]), tensor([0., 0., 1.]))


In [4]:
device = torch.device('cuda')

# Use the nn package to define our model and loss function.
model = torch.nn.Linear(9, 3)
model = model.to(device)

cost = torch.nn.MSELoss(reduction='sum')

# optimizer which Tensors it should update.
learning_rate = 1e-4
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# dataset!
dataloader = DataLoader(squares, batch_size=128)

epochs = 300

In [6]:
for t in range(epochs):
    for batch, (X, Y) in enumerate(dataloader):
        X, Y = X.to(device) / 255, Y.to(device)
        optimizer.zero_grad()
        pred = model(X)
        loss = cost(pred, Y)
        loss.backward()
        optimizer.step()

    if t % 50 == 0:
        print('l: {:>8f}, (e {})'.format(loss.item(), t))

l: 36.942242, (e 0)
l: 36.934631, (e 100)
l: 36.935852, (e 200)
Parameter containing:
tensor([[ 0.6519,  0.5624,  0.5673, -0.3080, -0.2763, -0.2851, -0.2849, -0.3109,
         -0.2483],
        [-0.3788, -0.2972, -0.2607,  0.5261,  0.5484,  0.6179, -0.3166, -0.2627,
         -0.3024],
        [-0.2692, -0.2622, -0.3026, -0.2138, -0.2685, -0.3290,  0.6044,  0.5776,
          0.5539]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.3050, 0.3893, 0.2889], device='cuda:0', requires_grad=True)


In [7]:
print("W's and b's:")
for p in model.parameters():
    print(p)

W's and b's:
Parameter containing:
tensor([[ 0.6519,  0.5624,  0.5673, -0.3080, -0.2763, -0.2851, -0.2849, -0.3109,
         -0.2483],
        [-0.3788, -0.2972, -0.2607,  0.5261,  0.5484,  0.6179, -0.3166, -0.2627,
         -0.3024],
        [-0.2692, -0.2622, -0.3026, -0.2138, -0.2685, -0.3290,  0.6044,  0.5776,
          0.5539]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.3050, 0.3893, 0.2889], device='cuda:0', requires_grad=True)
